import {
  Item,
  Customer,
  Supplier,
  ExpenseCategory,
  UserProfile,
  StoreSettings,
  StockMovement,
  AccountMovement,
  TreasuryMovement,
} from '../types';

export const INITIAL_USERS: UserProfile[] = [
  { id: 'u1', username: 'admin', full_name: 'أ/ محمود الشريف (المدير)', role: 'admin', is_active: true, avatar_color: 'amber' },
  { id: 'u2', username: 'accountant', full_name: 'أ/ سمير فاروق (المحاسب)', role: 'accountant', is_active: true, avatar_color: 'emerald' },
  { id: 'u3', username: 'cashier', full_name: 'أ/ وليد كمال (الكاشير)', role: 'cashier', is_active: true, avatar_color: 'orange' },
];

export const INITIAL_SETTINGS: StoreSettings = {
  store_name: 'العموري لقطع غيار السيارات',
  phone: '01012345678 - 0224567890',
  address: 'شارع دمشق - مصر الجديدة - القاهرة',
  commercial_number: 'س.ت: 184920',
  tax_number: 'ب.ض: 423-908-112',
  invoice_footer: 'البضاعة المباعة ترد وتستبدل خلال 14 يوم بالعلبة الأصلية والفاتورة. شكراً لثقتكم الغالية.',
  thermal_footer: 'شكراً لتعاملكم مع العموري لقطع غيار السيارات - يسعدنا دائماً خدمتكم',
  allow_negative_stock: false,
  default_cash_customer_id: 'cust-4',
  sales_prefix: 'S',
  purchase_prefix: 'P',
  auto_lock_minutes: 15,
};

export const INITIAL_EXPENSE_CATEGORIES: ExpenseCategory[] = [
  { id: 'exp_cat_1', name: 'إيجار المحل والمخزن' },
  { id: 'exp_cat_2', name: 'كهرباء ومياه وغاز' },
  { id: 'exp_cat_3', name: 'مرتبات وعمالة' },
  { id: 'exp_cat_4', name: 'مصاريف شحن وتوصيل' },
  { id: 'exp_cat_5', name: 'بوفيه وضيافة ونظافة' },
  { id: 'exp_cat_6', name: 'صيانة ومعدات وأدوات' },
  { id: 'exp_cat_7', name: 'رسوم وضرائب حكومية' },
];

export const INITIAL_ITEMS: Item[] = [
  {
    id: 'item-1',
    code: 'TY-04465',
    barcode: '622100234501',
    name: 'طقم تيل فرامل أمامي سيراميك',
    brand: 'Bosch (ألماني)',
    car_model: 'تويوتا كورولا 2014 - 2021',
    oem_number: '04465-02220',
    unit: 'طقم',
    cost_price: 650.0,
    retail_price: 880.0,
    wholesale_price: 780.0,
    min_stock: 4,
    shelf_location: 'الرف A-12',
    initial_stock: 18,
    created_at: '2026-09-01T08:00:00Z',
  },
  {
    id: 'item-2',
    code: 'HY-25100',
    barcode: '622100234502',
    name: 'طلمبة مياه تبريد موتور أصلية',
    brand: 'GMB (كوري)',
    car_model: 'هيونداي فيرنا / ماتركس 1600cc',
    oem_number: '25100-26900',
    unit: 'قطعة',
    cost_price: 720.0,
    retail_price: 950.0,
    wholesale_price: 850.0,
    min_stock: 3,
    shelf_location: 'الرف B-04',
    initial_stock: 12,
    created_at: '2026-09-01T08:00:00Z',
  },
  {
    id: 'item-3',
    code: 'KIA-55300',
    barcode: '622100234503',
    name: 'مساعد خلفي غاز عالي التحمل',
    brand: 'Mando (كوري أصلي)',
    car_model: 'كيا سيراتو 2010 - 2017',
    oem_number: '55300-1M000',
    unit: 'قطعة',
    cost_price: 1100.0,
    retail_price: 1450.0,
    wholesale_price: 1300.0,
    min_stock: 2,
    shelf_location: 'الرف C-01',
    initial_stock: 6,
    created_at: '2026-09-01T08:00:00Z',
  },
  {
    id: 'item-4',
    code: 'NS-13028',
    barcode: '622100234504',
    name: 'سير كاتينة وتقسيمة مقوى',
    brand: 'Gates (أمريكي)',
    car_model: 'نيسان صني N17 / تيدا',
    oem_number: '13028-1KT0A',
    unit: 'قطعة',
    cost_price: 340.0,
    retail_price: 490.0,
    wholesale_price: 430.0,
    min_stock: 5,
    shelf_location: 'الرف A-03',
    initial_stock: 15,
    created_at: '2026-09-01T08:00:00Z',
  },
  {
    id: 'item-5',
    code: 'MT-MD360',
    barcode: '622100234505',
    name: 'فلتر زيت محرك أصلي ياباني',
    brand: 'Denso (ياباني)',
    car_model: 'ميتسوبيشي لانسر بومة / شارك',
    oem_number: 'MD360935',
    unit: 'قطعة',
    cost_price: 160.0,
    retail_price: 240.0,
    wholesale_price: 200.0,
    min_stock: 10,
    shelf_location: 'الرف D-05',
    initial_stock: 35,
    created_at: '2026-09-01T08:00:00Z',
  },
  {
    id: 'item-6',
    code: 'NGK-IFR6',
    barcode: '622100234506',
    name: 'طقم بوجيهات إيريديوم ليزر (4 شمعات)',
    brand: 'NGK (ياباني أصلي)',
    car_model: 'تويوتا / هيونداي / كيا ياباني وكوري',
    oem_number: 'IFR6T11-4966',
    unit: 'طقم',
    cost_price: 820.0,
    retail_price: 1100.0,
    wholesale_price: 980.0,
    min_stock: 4,
    shelf_location: 'الرف A-08',
    initial_stock: 8,
    created_at: '2026-09-01T08:00:00Z',
  },
  {
    id: 'item-7',
    code: 'VL-82638',
    barcode: '622100234507',
    name: 'طقم دبرياج كامل (ديسك + اسطوانة + بلية)',
    brand: 'Valeo (فرنسي أصلي)',
    car_model: 'رينو لوجان / سانديرو 1600cc',
    oem_number: '826388',
    unit: 'طقم',
    cost_price: 2400.0,
    retail_price: 3150.0,
    wholesale_price: 2850.0,
    min_stock: 2,
    shelf_location: 'الرف E-02',
    initial_stock: 3,
    created_at: '2026-09-01T08:00:00Z',
  },
  {
    id: 'item-8',
    code: 'DP-81110',
    barcode: '622100234508',
    name: 'فانوس أمامي يمين كريستال أسود',
    brand: 'Depo (تايواني درجة أولى)',
    car_model: 'تويوتا كورولا 2015',
    oem_number: '81110-02B50',
    unit: 'قطعة',
    cost_price: 1850.0,
    retail_price: 2400.0,
    wholesale_price: 2150.0,
    min_stock: 1,
    shelf_location: 'الرف F-10',
    initial_stock: 2,
    created_at: '2026-09-01T08:00:00Z',
  },
];

export const INITIAL_CUSTOMERS: Customer[] = [
  {
    id: 'cust-1',
    name: 'مركز صيانة الأمل الحديثة (م. أحمد)',
    phone: '01011112222',
    address: 'شارع الطيران - مدينة نصر - القاهرة',
    opening_balance: 4500.0,
    credit_limit: 15000.0,
    notes: 'عميل مميز - سداد أسبوعي بالكامل',
    created_at: '2026-09-01T08:00:00Z',
  },
  {
    id: 'cust-2',
    name: 'ورشة الأسطى حسن العفشجي',
    phone: '01223334444',
    address: 'الحرفيين - بلوك 12 ورشة 4',
    opening_balance: 2850.0,
    credit_limit: 8000.0,
    notes: 'يشتري تيل فرامل ومساعدين بكثرة',
    created_at: '2026-09-01T08:00:00Z',
  },
  {
    id: 'cust-3',
    name: 'كابتن طارق عبد العزيز (أوبر)',
    phone: '01556677889',
    address: 'عين شمس - القاهرة',
    opening_balance: 650.0,
    credit_limit: 2000.0,
    notes: 'سيارة تويوتا كورولا 2018',
    created_at: '2026-09-05T10:00:00Z',
  },
  {
    id: 'cust-4',
    name: 'عميل نقدي (شباك البيع)',
    phone: '-',
    address: 'المحل',
    opening_balance: 0.0,
    credit_limit: 0.0,
    notes: 'مبيعات الكاش المباشرة بدون تسجيل مديونية',
    created_at: '2026-09-01T08:00:00Z',
  },
];

export const INITIAL_SUPPLIERS: Supplier[] = [
  {
    id: 'supp-1',
    name: 'شركة الأهرام لاستيراد قطع الغيار الأصلية',
    phone: '01001234567',
    address: 'التوفيقية - وسط البلد - القاهرة',
    opening_balance: 14200.0, // له علينا
    notes: 'موزع معتمد لبوش ومندو وجيتس',
    created_at: '2026-09-01T08:00:00Z',
  },
  {
    id: 'supp-2',
    name: 'مؤسسة النور لمستلزمات السيارات اليابانية',
    phone: '01122334455',
    address: 'شارع رمسيس - القاهرة',
    opening_balance: 8500.0,
    notes: 'موزع دينسو وديبو',
    created_at: '2026-09-01T08:00:00Z',
  },
  {
    id: 'supp-3',
    name: 'التوكيل الهندسي للفرامل والدبرياج (فاليو)',
    phone: '01298765432',
    address: 'المنطقة الصناعية - العاشر من رمضان',
    opening_balance: 0.0,
    notes: 'وكيل فاليو فرنسا',
    created_at: '2026-09-01T08:00:00Z',
  },
];

// Initial movement logs ensuring 100% calculation compliance
export const getInitialMovements = () => {
  const stockMovements: StockMovement[] = INITIAL_ITEMS.map((item) => ({
    id: `sm-init-${item.id}`,
    item_id: item.id,
    item_name: item.name,
    movement_type: 'initial',
    doc_type: 'رصيد أول المدة',
    doc_id: 'init',
    doc_number: 'INIT-001',
    party_name: 'جرد افتتاحي',
    quantity_in: item.initial_stock,
    quantity_out: 0,
    unit_price: item.cost_price,
    running_balance: item.initial_stock,
    date: '2026-09-01',
    notes: 'رصيد بضاعة أول المدة',
    created_at: '2026-09-01T08:00:00Z',
  }));

  const accountMovements: AccountMovement[] = [
    {
      id: 'am-init-c1',
      party_type: 'customer',
      party_id: 'cust-1',
      party_name: 'مركز صيانة الأمل الحديثة (م. أحمد)',
      movement_type: 'initial',
      doc_type: 'رصيد افتتاحي',
      doc_id: 'init-c1',
      doc_number: 'OPEN-01',
      debit: 4500.0,
      credit: 0,
      balance_after: 4500.0,
      date: '2026-09-01',
      notes: 'رصيد سابق افتتاحي عليه',
      created_at: '2026-09-01T08:00:00Z',
    },
    {
      id: 'am-init-c2',
      party_type: 'customer',
      party_id: 'cust-2',
      party_name: 'ورشة الأسطى حسن العفشجي',
      movement_type: 'initial',
      doc_type: 'رصيد افتتاحي',
      doc_id: 'init-c2',
      doc_number: 'OPEN-02',
      debit: 2850.0,
      credit: 0,
      balance_after: 2850.0,
      date: '2026-09-01',
      notes: 'رصيد سابق افتتاحي عليه',
      created_at: '2026-09-01T08:00:00Z',
    },
    {
      id: 'am-init-c3',
      party_type: 'customer',
      party_id: 'cust-3',
      party_name: 'كابتن طارق عبد العزيز (أوبر)',
      movement_type: 'initial',
      doc_type: 'رصيد افتتاحي',
      doc_id: 'init-c3',
      doc_number: 'OPEN-03',
      debit: 650.0,
      credit: 0,
      balance_after: 650.0,
      date: '2026-09-05',
      notes: 'رصيد سابق افتتاحي عليه',
      created_at: '2026-09-05T08:00:00Z',
    },
    {
      id: 'am-init-s1',
      party_type: 'supplier',
      party_id: 'supp-1',
      party_name: 'شركة الأهرام لاستيراد قطع الغيار الأصلية',
      movement_type: 'initial',
      doc_type: 'رصيد افتتاحي',
      doc_id: 'init-s1',
      doc_number: 'OPEN-S01',
      debit: 0,
      credit: 14200.0,
      balance_after: 14200.0,
      date: '2026-09-01',
      notes: 'رصيد سابق افتتاحي له علينا',
      created_at: '2026-09-01T08:00:00Z',
    },
    {
      id: 'am-init-s2',
      party_type: 'supplier',
      party_id: 'supp-2',
      party_name: 'مؤسسة النور لمستلزمات السيارات اليابانية',
      movement_type: 'initial',
      doc_type: 'رصيد افتتاحي',
      doc_id: 'init-s2',
      doc_number: 'OPEN-S02',
      debit: 0,
      credit: 8500.0,
      balance_after: 8500.0,
      date: '2026-09-01',
      notes: 'رصيد سابق افتتاحي له علينا',
      created_at: '2026-09-01T08:00:00Z',
    },
  ];

  const treasuryMovements: TreasuryMovement[] = [
    {
      id: 'tm-init-1',
      movement_type: 'initial',
      doc_type: 'رصيد افتتاحي',
      doc_id: 'init-tr',
      doc_number: 'TR-OPEN',
      party_name: 'الخزينة الرئيسية',
      amount_in: 25000.0,
      amount_out: 0,
      balance_after: 25000.0,
      date: '2026-09-01',
      notes: 'رصيد خزينة افتتاحي للمحل',
      created_by: 'المدير العام',
      created_at: '2026-09-01T08:00:00Z',
    },
  ];

  return { stockMovements, accountMovements, treasuryMovements };
};
